export const minimaxVoices = [
  // English
  "English_Trustworth_Man",
  "English_Aussie_Bloke",
  "English_CalmWoman",
  "English_UpsetGirl",
  "English_Gentle-voiced_man",
  "English_Whispering_girl",
  "English_Diligent_Man",
  "English_Graceful_Lady",
  "English_ReservedYoungMan",
  "English_PlayfulGirl",
  "English_ManWithDeepVoice",
  "English_MaturePartner",
  "English_FriendlyPerson",
  "English_MatureBoss",
  "English_Debator",
  "English_LovelyGirl",
  "English_Steadymentor",
  "English_Deep-VoicedGentleman",
  "English_Wiselady",
  "English_CaptivatingStoryteller",
  "English_DecentYoungMan",
  "English_SentimentalLady",
  "English_ImposingManner",
  "English_SadTeen",
  "English_PassionateWarrior",
  "English_WiseScholar",
  "English_Soft-spokenGirl",
  "English_SereneWoman",
  "English_ConfidentWoman",
  "English_PatientMan",
  "English_Comedian",
  "English_BossyLeader",
  "English_Strong-WilledBoy",
  "English_StressedLady",
  "English_AssertiveQueen",
  "English_AnimeCharacter",
  "English_Jovialman",
  "English_WhimsicalGirl",
  "English_Kind-heartedGirl",

  // Chinese
  "Chinese (Mandarin)_Reliable_Executive",
  "Chinese (Mandarin)_News_Anchor",
  "Chinese (Mandarin)_Unrestrained_Young_Man",
  "Chinese (Mandarin)_Mature_Woman",
  "Arrogant_Miss",
  "Robot_Armor",
  "Chinese (Mandarin)_Kind-hearted_Antie",
  "Chinese (Mandarin)_Refreshing_Young_Man",
  "Chinese (Mandarin)_HK_Flight_Attendant",
  "Chinese (Mandarin)_Humorous_Elder",
  "Chinese (Mandarin)_Gentleman",
  "Chinese (Mandarin)_Warm_Bestie",
  "Chinese (Mandarin)_Stubborn_Friend",
  "Chinese (Mandarin)_Sweet_Lady",
  "Chinese (Mandarin)_Southern_Young_Man",
  "Chinese (Mandarin)_Wise_Women",
  "Chinese (Mandarin)_Gentle_Youth",
  "Chinese (Mandarin)_Warm_Girl",
  "Chinese (Mandarin)_Male_Announcer",
  "Chinese (Mandarin)_Kind-hearted_Elder",
  "Chinese (Mandarin)_Cute_Spirit",
  "Chinese (Mandarin)_Radio_Host",
  "Chinese (Mandarin)_Lyrical_Voice",
  "Chinese (Mandarin)_Straightforward_Boy",
  "Chinese (Mandarin)_Sincere_Adult",
  "Chinese (Mandarin)_Gentle_Senior",
  "Chinese (Mandarin)_Crisp_Girl",
  "Chinese (Mandarin)_Pure-hearted_Boy",
  "Chinese (Mandarin)_Soft_Girl",
  "Chinese (Mandarin)_IntellectualGirl",
  "Chinese (Mandarin)_Warm_HeartedGirl",
  "Chinese (Mandarin)_Laid_BackGirl",
  "Chinese (Mandarin)_ExplorativeGirl",
  "Chinese (Mandarin)_Warm-HeartedAunt",
  "Chinese (Mandarin)_BashfulGirl",

  // Japanese
  "Japanese_IntellectualSenior",
  "Japanese_DecisivePrincess",
  "Japanese_LoyalKnight",
  "Japanese_DominantMan",
  "Japanese_SeriousCommander",
  "Japanese_ColdQueen",
  "Japanese_DependableWoman",
  "Japanese_GentleButler",
  "Japanese_KindLady",
  "Japanese_CalmLady",
  "Japanese_OptimisticYouth",
  "Japanese_GenerousIzakayaOwner",
  "Japanese_SportyStudent",
  "Japanese_InnocentBoy",
  "Japanese_GracefulMaiden",

  // Cantonese
  "Cantonese_ProfessionalHost（F)",
  "Cantonese_GentleLady",
  "Cantonese_ProfessionalHost（M)",
  "Cantonese_PlayfulMan",
  "Cantonese_CuteGirl",
  "Cantonese_KindWoman",

  // Korean
  "Korean_SweetGirl",
  "Korean_CheerfulBoyfriend",
  "Korean_EnchantingSister",
  "Korean_ShyGirl",
  "Korean_ReliableSister",
  "Korean_StrictBoss",
  "Korean_SassyGirl",
  "Korean_ChildhoodFriendGirl",
  "Korean_PlayboyCharmer",
  "Korean_ElegantPrincess",
  "Korean_BraveFemaleWarrior",
  "Korean_BraveYouth",
  "Korean_CalmLady",
  "Korean_EnthusiasticTeen",
  "Korean_SoothingLady",
  "Korean_IntellectualSenior",
  "Korean_LonelyWarrior",
  "Korean_MatureLady",
  "Korean_InnocentBoy",
  "Korean_CharmingSister",
  "Korean_AthleticStudent",
  "Korean_BraveAdventurer",
  "Korean_CalmGentleman",
  "Korean_WiseElf",
  "Korean_CheerfulCoolJunior",
  "Korean_DecisiveQueen",
  "Korean_ColdYoungMan",
  "Korean_MysteriousGirl",
  "Korean_QuirkyGirl",
  "Korean_ConsiderateSenior",
  "Korean_CheerfulLittleSister",
  "Korean_DominantMan",
  "Korean_AirheadedGirl",
  "Korean_ReliableYouth",
  "Korean_FriendlyBigSister",
  "Korean_GentleBoss",
  "Korean_ColdGirl",
  "Korean_HaughtyLady",
  "Korean_CharmingElderSister",
  "Korean_IntellectualMan",
  "Korean_CaringWoman",
  "Korean_WiseTeacher",
  "Korean_ConfidentBoss",
  "Korean_AthleticGirl",
  "Korean_PossessiveMan",
  "Korean_GentleWoman",
  "Korean_CockyGuy",
  "Korean_ThoughtfulWoman",
  "Korean_OptimisticYouth",

  // Spanish
  "Spanish_SereneWoman",
  "Spanish_MaturePartner",
  "Spanish_CaptivatingStoryteller",
  "Spanish_Narrator",
  "Spanish_WiseScholar",
  "Spanish_Kind-heartedGirl",
  "Spanish_DeterminedManager",
  "Spanish_BossyLeader",
  "Spanish_ReservedYoungMan",
  "Spanish_ConfidentWoman",
  "Spanish_ThoughtfulMan",
  "Spanish_Strong-WilledBoy",
  "Spanish_SophisticatedLady",
  "Spanish_RationalMan",
  "Spanish_AnimeCharacter",
  "Spanish_Deep-tonedMan",
  "Spanish_Fussyhostess",
  "Spanish_SincereTeen",
  "Spanish_FrankLady",
  "Spanish_Comedian",
  "Spanish_Debator",
  "Spanish_ToughBoss",
  "Spanish_Wiselady",
  "Spanish_Steadymentor",
  "Spanish_Jovialman",
  "Spanish_SantaClaus",
  "Spanish_Rudolph",
  "Spanish_Intonategirl",
  "Spanish_Arnold",
  "Spanish_Ghost",
  "Spanish_HumorousElder",
  "Spanish_EnergeticBoy",
  "Spanish_WhimsicalGirl",
  "Spanish_StrictBoss",
  "Spanish_ReliableMan",
  "Spanish_SereneElder",
  "Spanish_AngryMan",
  "Spanish_AssertiveQueen",
  "Spanish_CaringGirlfriend",
  "Spanish_PowerfulSoldier",
  "Spanish_PassionateWarrior",
  "Spanish_ChattyGirl",
  "Spanish_RomanticHusband",
  "Spanish_CompellingGirl",
  "Spanish_PowerfulVeteran",
  "Spanish_SensibleManager",
  "Spanish_ThoughtfulLady",

  // French
  "French_Male_Speech_New",
  "French_Female_News Anchor",
  "French_CasualMan",
  "French_MovieLeadFemale",
  "French_FemaleAnchor",
  "French_MaleNarrator",

  // Indonesian
  "Indonesian_SweetGirl",
  "Indonesian_ReservedYoungMan",
  "Indonesian_CharmingGirl",
  "Indonesian_CalmWoman",
  "Indonesian_ConfidentWoman",
  "Indonesian_CaringMan",
  "Indonesian_BossyLeader",
  "Indonesian_DeterminedBoy",
  "Indonesian_GentleGirl",

  // German
  "German_FriendlyMan",
  "German_SweetLady",
  "German_PlayfulMan",

  // Russian
  "Russian_HandsomeChildhoodFriend",
  "Russian_BrightHeroine",
  "Russian_AmbitiousWoman",
  "Russian_ReliableMan",
  "Russian_CrazyQueen",
  "Russian_PessimisticGirl",
  "Russian_AttractiveGuy",
  "Russian_Bad-temperedBoy",

  // Italian
  "Italian_BraveHeroine",
  "Italian_Narrator",
  "Italian_WanderingSorcerer",
  "Italian_DiligentLeader",

  // Others
  "Dutch_kindhearted_girl",
  "Dutch_bossy_leader",
  "Vietnamese_kindhearted_girl",
  "Arabic_CalmWoman",
  "Arabic_FriendlyGuy",
  "Turkish_CalmWoman",
  "Turkish_Trustworthyman",
  "Ukrainian_CalmWoman",
] as const;

export const qwenVoices = ["Cherry", "Ethan", "Serena", "Dylan"] as const;

export type MinimaxVoice = (typeof minimaxVoices)[number];
export type QwenVoice = (typeof qwenVoices)[number];
